-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    user_id smallserial NOT NULL,
    user_name character varying(100) NOT NULL,
    CONSTRAINT pm_user_id PRIMARY KEY (user_id),
    CONSTRAINT uk_username UNIQUE (user_name)
);

CREATE TABLE IF NOT EXISTS public.book
(
    book_id smallserial NOT NULL,
    book_name text NOT NULL,
    author_name character varying NOT NULL,
    pages integer NOT NULL,
    genre character varying NOT NULL,
    availability boolean NOT NULL,
    book_date_added timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_book_id PRIMARY KEY (book_id),
    CONSTRAINT uk_book_id UNIQUE (book_id, book_name)
);

CREATE TABLE IF NOT EXISTS public.command
(
    book_id integer,
    user_id integer,
    mark_read boolean,
    mark_reading boolean,
    mark_will_read boolean,
    fav_book boolean
);

ALTER TABLE IF EXISTS public.command
    ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.command
    ADD CONSTRAINT fk_book_id FOREIGN KEY (book_id)
    REFERENCES public.book (book_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;